version: "3.8"

services:
  ollama:
    build: .
    container_name: ollama
    image: ollama/ollama
    pull_policy: always
    healthcheck:
      test: ollama --version || exit 1
      interval: 10s
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
